// Generated by CoffeeScript 1.7.1
var grapher, msgpack, subSocket, zmq;

zmq = require('zmq');

msgpack = require('msgpack');

subSocket = zmq.socket('sub');

subSocket.connect('tcp://127.0.0.1:5555');

subSocket.subscribe('');

subSocket.on('message', function(data) {
  var unpackedData;
  unpackedData = msgpack.unpack(data);
  switch (unpackedData.event_type) {
    case 'obj_created':
      return grapher.addData(unpackedData.payload);
    case "gc_stats":
      return grapher.updateGcStats(unpackedData.payload);
  }
});

grapher = new Graph('#chart');
