// Generated by CoffeeScript 1.7.1
var BrowserWindow, aggregator, app, mainWindow;

app = require('app');

aggregator = require('./aggregator');

BrowserWindow = require('browser-window');

require('crash-reporter').start();

mainWindow = null;

app.on('window-all-closed', function() {
  if (!(process.platform === 'darwin')) {
    return app.quit();
  }
});

app.on('ready', function() {
  var Agg, agg;
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  });
  mainWindow.loadUrl("file://" + __dirname + "/index.html");
  mainWindow.on('closed', function() {
    return mainWindow = null;
  });
  Agg = aggregator();
  agg = new Agg;
  return agg.run([]);
});
